### ISSUE TITLE
Vectorized objective function extensions added (please commit it in the master)

### ISSUE THREAD

**Issue by aiAdrian** [7ossam81/EvoloPy#10]
Dear all

I just added vectorized=False and modified all optimizer to execute in vectorized way the objective function. In additional the python implementation does not store solution individual best thus i also added it. 

I am not sure, but you have to check whether all "best position" vectors get copied in python (especially for numpy objects) otherwise the alignment will only be set by reference. I didn't yet reviewed everthing up to now. 

Kind regards 
Adrian Egli 

[EvoloPy.zip](https://github.com/7ossam81/EvoloPy/files/1578843/EvoloPy.zip)

**Comment by 7ossam81** [comment]
Thank you for your contribution. Vectorizing the objective function is a good idea. Regarding the best individual, it is stored at the last index of the convergence curve. 
Please make a pull request to push your contribution to the master.

Regards,
Hossam

**Comment by aiAdrian** [comment]
Hi Hossam,

Please to it for me. Because i am not sure the contributed code is correct implemented. 

Regards
Adrian

**Comment by RaneemQaddoura** [comment]
The copy issue for the python vectors is solved in several old commits
Thank you for bringing this to our attention.
