### ISSUE TITLE
About a license issue...

### ISSUE THREAD

**Issue by JHKim123** [7ossam81/EvoloPy#12]
Hi, I am a graduate student studying about optimization in Korea. I want to use this open source in a project to help student studying about optimization, but might be also used by some commercial companies. So I'm wondering about the license things like permissions, limitations, or conditions to use this open source.
Would you state about the license of the EvoloPy?

**Comment by RaneemQaddoura** [comment]
Thank you for your interest in EvoloPy
Please refer to the Apache License 2.0 provided
