### ISSUE TITLE
Is there any detailed availble code samples

### ISSUE THREAD

**Issue by AymanNabih** [7ossam81/EvoloPy#20]
Dear sir
I am a masters degree student who wishes to use your package in the implementation of my research 
however there is one simple difficulty which is the lack of any detailed code samples that give some guidence on how to use your package efficently
regards
Ayman

**Comment by RaneemQaddoura** [comment]
Hi Ayman
I know this might be a very late reply
The framework is now more mature and it includes an 'example.py' file as a code sample
