### ISSUE TITLE
multivariables only have one constraint set?

### ISSUE THREAD

**Issue by jbae11** [7ossam81/EvoloPy#26]
hello, I was looking over your code, and I was wondering if all the variables in a function share the same `lb` and `ub`. It seems like that is the case. Is there a way to have it so that the user can define constraints for each variable?

For example, if:
```
def objf(x):
    return x[0]+x[1]
```
`lb` could be an array or length 2 (or `ndim`), like [-10, 20]
and the same with `ub`.

If I am completely mistaken and there already exists this capability, please let me know.

If not, I would love to contribute to this repo by making a PR. Let me know if that is the case.

thanks!

**Comment by 7ossam81** [comment]
@jbae11 

Thank you for your contribution ! Good suggestion.

**Comment by RaneemQaddoura** [comment]
In the current implementation, you can set different upper/lower bounds for each variable. For example, for f23, you can update the getFunctionDetails function for f23 in benchmarks.py to 
"F23": ["F23", [0,0,0,0], [10,10,10,10], 4],
