### ISSUE TITLE
Example or document 

### ISSUE THREAD

**Issue by sadiqdu** [7ossam81/EvoloPy#42]
Dear Authors,
I would like to use EvoloPy for my own dataset. Can you send me an example or documents on how I can use the EvoloPy?

Regards,
Dr Sadiq Hussain,
India

**Comment by RaneemQaddoura** [comment]
Hi Dr Sadiq,

you can find the details in this paper:
https://www.scitepress.org/Papers/2016/60482/60482.pdf

Also, for the example, you can run the optimizer.py and setup your experiment by selecting the optmizers, the benchmarks, number of runs, number of iterations, and population size. As mentioned in the readme file:

To choose PSO optimizer for your experiment, change the PSO flag to true and others to false.

Select optimizers:    
PSO= True  
MVO= False  
GWO = False  
MFO= False  
CS= False    
...
After that, Select benchmark function:

F1=True  
F2=False  
F3=False  
F4=False  
F5=False  
F6=False  
....  
Change NumOfRuns, PopulationSize, and Iterations variables as you want:

NumOfRuns=10  
PopulationSize = 50  
Iterations= 1000
