### ISSUE TITLE
bat.py____ line62--65

### ISSUE THREAD

**Issue by owais-ch** [7ossam81/EvoloPy#43]
# Find the initial best solution
    fmin = min(Fitness)
    I=numpy.argmin(fmin)   
    best=Sol[I,:]

Here fmin will be a scalar, so all the time I will be zero Am I right?
It should be I=numpy.argmin(Fitness)

Can you please comment on it

**Comment by RaneemQaddoura** [comment]
Yes you are right
I'll update the BAT.py file accordingly
Thank you for your feedback

**Comment by owais-ch** [comment]
Hi,
    Thank you for your reply.

Regards
Owais
