### ISSUE TITLE
Urgent Question

### ISSUE THREAD

**Issue by brijeshsaraswat** [7ossam81/EvoloPy#45]
Thanks for great repo. 
I have a data of numpy array with shape = (10000,10).Can you pls tell how can i do the benchmarking on my data?

**Comment by 7ossam81** [comment]
What task you are aiming for? EvoloPy is designed for global optimization.

**Comment by brijeshsaraswat** [comment]
Looking to cluster dataset using GWO and PSO optimization and even obtain final clusters in general. Could you let me know how to use my dataset in your code?
Thanks in advance.

**Comment by RaneemQaddoura** [comment]
You can use EvoCluster, which we've done as an extension of EvoloPy for clustering.
Source code: https://github.com/RaneemQaddoura/EvoCluster
Description: https://youtu.be/3DYIdxILZaw
Demo: https://youtu.be/eMEuLzwq5x4
Webpage: http://evo-ml.com/2019/10/25/evocluster/
