### ISSUE TITLE
Can't run it.

### ISSUE THREAD

**Issue by wellinton-capixaba** [7ossam81/EvoloPy#53]
executing  "python optimizer.py" returns: "No module named optimizers.PSO"
How to solve it?

**Comment by wellinton-capixaba** [comment]
Superb support!

**Comment by 7ossam81** [comment]
The code works fine for me. Try to install all requirements. Let me know if you still have problems.

**Comment by wellinton-capixaba** [comment]
Well, it didn't for me. Anyway, I modified the source so it could run independently from the other source files.
