### ISSUE TITLE
F12 is wrong

### ISSUE THREAD

**Issue by ZongSingHuang** [7ossam81/EvoloPy#61]
fixed:
![002](https://user-images.githubusercontent.com/58209813/104123116-2109a200-5384-11eb-9cac-1f3b57655204.PNG)

ref:
![001](https://user-images.githubusercontent.com/58209813/104123059-d1c37180-5383-11eb-9e48-f1599256c7f5.PNG)

**Comment by RaneemQaddoura** [comment]
Thanks @ZongSingHuang 
Solved Now
