### ISSUE TITLE
F13 is wrong

### ISSUE THREAD

**Issue by ZongSingHuang** [7ossam81/EvoloPy#62]
fixed:
![001](https://user-images.githubusercontent.com/58209813/104125444-b8292680-5391-11eb-8bca-f6a4f901234a.PNG)

ref:
[SEYEDALI MIRJALILI(GWO)](https://seyedalimirjalili.com/gwo)
![003](https://user-images.githubusercontent.com/58209813/104124249-bf006b00-538a-11eb-8fe1-97158ec946e4.PNG)

**Comment by RaneemQaddoura** [comment]
Thank you @ZongSingHuang for your feedback. 
I can see that both functions are identical; one implemented in Matlab and the other in Python.
Please let me know if I am missing something
Thank you

**Comment by RaneemQaddoura** [comment]
Thank you @ZongSingHuang 
Solved now
