### ISSUE TITLE
F21, F21, F23 are wrong

### ISSUE THREAD

**Issue by ZongSingHuang** [7ossam81/EvoloPy#63]
fixed:
![image](https://user-images.githubusercontent.com/58209813/104128410-56bd8380-53a2-11eb-8882-2f2e443ac007.png)

![image](https://user-images.githubusercontent.com/58209813/104128368-27a71200-53a2-11eb-901d-737cdb28d0c6.png)

![image](https://user-images.githubusercontent.com/58209813/104128374-2e358980-53a2-11eb-8234-da99354783af.png)

**Comment by RaneemQaddoura** [comment]
Thank you @ZongSingHuang 
Solved now
