### ISSUE TITLE
User defined-MILP

### ISSUE THREAD

**Issue by LeonXiang** [7ossam81/EvoloPy#67]
Hi, I have skimmed most of the codes in EvoloPy, and I think it outstanding from my perspective as a freshman. However, I wanna to solve a Mixed-Integer Linear Programming problem with binary variants which have over 4 subscripts. If so could you please tell me if MILP is proper here or kindly explain how that could be done? Thank you very much.

**Comment by RaneemQaddoura** [comment]
Thank you for your interest in EvoloPy
Yes, EvoloPy is the proper framework to do it.
You need to add a new function to the code as follows:
You just need to do the following:

1. - Add your function to the 'benchmark.py' file
2. - Add the function (name, lower bound, upper bound, and dimension) to 'getFunctionDetails' function at the 'benchmark.py' file
3. - Add the function name to the 'objectivefunc' list at 'example.py' file

Hope this helps

**Comment by RaneemQaddoura** [comment]
Please watch this video for an illustration of how to add a function to the framework:
https://www.youtube.com/watch?v=CGFRbbR4vvI
