### ISSUE TITLE
I need help can you tell me the names of benchmark functions you used 

### ISSUE THREAD

**Issue by AditSoni** [7ossam81/EvoloPy#68]
can you please tell me the names of benchmark functions defined in benchmarks.py in evolopy

**Comment by RaneemQaddoura** [comment]
There are not defined by names. However, the benchmark formulas can be found at the EvoloPy page: http://evo-ml.com/evolopy/
Benchmark Functions: http://evo-ml.com/wp-content/uploads/2021/04/EvoloPy_Benchmark_functions.pdf
You can also find them through the GWO paper: https://doi.org/10.1016/j.advengsoft.2013.12.007

**Comment by AditSoni** [comment]
Thanks !! appreciated

**Comment by RaneemQaddoura** [comment]
Welcome
