### ISSUE TITLE
Relax python3 requirement

### ISSUE THREAD

**Issue by ericjster** [7ossam81/EvoloPy#7]
The code seems to work in python2. I only saw issues with PEP238, integer division behavior, in FFA.py, alpha_new. I'm not a python3 user but I think all that is needed is to add these lines at the front of each routine:
<pre>
from __future__ import division
from __future__ import print_function
</pre>
Or be explicit when doing floating point arithmetic, for example in alpha_new:
<pre> delta=1.-(10.**(-4.)/0.9)**(1./NGen); </pre>

**Comment by RaneemQaddoura** [comment]
Not applicable now. the code works for Python version 3
