### ISSUE TITLE
MFO Algorithm, the search agent number is hard coded.

### ISSUE THREAD

**Issue by Sylvexia** [7ossam81/EvoloPy#72]
in optimizer.py, the PopulatioinSize would not effect MFO algorithm since in optimzers/MFO.py , the N=50 overwrite the function parameter which was passed in.
I discover the issue when i was increasing the population size, and the benchmark time don't quite change

**Comment by RaneemQaddoura** [comment]
Thank you Sylvexia,
The issue is solved.
